print('Que sale de la cruza entre un mono y un pato')
input()
print('un monopatin!')
input()
print('Por que los pajaros vuelan pal sur?')
input()
print('porque caminando tendrian muchisimo!')
print()
print('En que se parecen una familia, un bombero y un barco?')
input()
print('no se, en que se parecen?')
input()
print('En que el bombero y el barco tienen casco.')
input()
print('y la familia?', end='')
print('-Bien, gracias.')

